### ISSUE TITLE
encounter error when resuming from a trained .pth file

### ISSUE THREAD

**Issue by sddai** [eric612/Mobilenet-YOLO-Pytorch#7]
i ran :
`python train.py --resume ./checkpoints/model_best_my_train.pth.tar`

and i got :
{'img_h': 352, 'img_w': 352, 'batch_size': 32, 'train_img_size': [[352, 352], [320, 320], [288, 288], [384, 384], [416, 416]], 'expand_scale': 2.1610954191879452, 'mosaic_num': [1, 4], 'iou_weighting': 0.021830872589525777, 'yolo': {'num_classes': 20, 'num_anchors': 3, 'ignore_thresh': [0.6076333316652263, 0.5623606200028424], 'iou_thresh': 0.5497280113447018, 'anchors': [[143, 265], [153, 121], [280, 279], [20, 37], [49, 94], [73, 201]], 'classes': 20, 'mask': [[0, 1, 2], [3, 4, 5]]}}
==> Resuming from checkpoint..
./checkpoints/model_best_my_train.pth.tar
Traceback (most recent call last):
  File "train2.py", line 433, in <module>
    main(params)
  File "train2.py", line 122, in main
    best_acc = checkpoint['best_acc']
TypeError: 'yolo' object is not subscriptable

would you pls figure out that how to get the right result? thanks a lot 💯

**Comment by eric612** [comment]
I removed the optimizer of 'model_best_my_train.pth.tar' , just only can be used in deploy or inference

[Intermediate save code](https://github.com/eric612/Mobilenet-YOLO-Pytorch/blob/main/train.py#L150-L157) 

[model_best save code](https://github.com/eric612/Mobilenet-YOLO-Pytorch/blob/main/train.py#L360-L363)

**Comment by TomTHChen** [comment]
ModuleNotFoundError: No module named 'models.voc.mobilenetv2'
Fixed by moving *.py models into /models/voc/.
